name: Controlling Execution Flow

on: 
    workflow_dispatch:
      inputs:
        pass-unit-tests:
          type: boolean
          description: Wether unit tests will pass or not
          default: true


jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and build
              run: echo "Listing and building projecy"

    unit-test:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Running unit test
              run: echo "Running test"
            - name: Fails tests
              if: ${{ !inputs.pass-unit-tests}}
              run: eit 1
              
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-test
        steps:
            - name: Deploy nonprod
              run: echo "Deploying to nonprod"

    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps: 
            - name: Running e2e test
              run: echo "Running e2e test"

    load-tests:
        runs-on: ubuntu latest
        
        needs:
            - deploy-nonprod
        steps:
            - name: Running load test
              run: echo "Running load tests"

    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying to prod
              run: echo "Deploying to prod"

