name: 2 - Worflow Events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 0 * * *' #run every 5 min
    workflow_dispatch:     #enable to trigger from the UI


jobs: 
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Show the trigger
              run: echo "I've been trigger by a(n) ${{github.event_name}}" #the name of the event that triggered this workflow

