name: Use Actions

on: workflow_dispatch 

jobs:
    build:
        runs-on: ubuntu-latest
        defaults: 
            run: 
                working-directory: 4-use-actions/react-app  #setup the default directory and not be included in another part of the shell (directory)

        
        steps:  #encounter workflow 
            - name: Checkout Code
              uses: actions/checkout@v4

            #- name: Printing folders
             # run: ls 

            - name: Setup Node
              uses:  actions/setup-node@v3
              with: 
                node-version: '20.x'

            - name: Install Dependencies
              run: npm ci
             # working-directory: 4-use-actions/react-app ###directory was set as default 

            - name: Run Unit Test
              run: npm run test
             # working-directory: 4-use-actions/react-app  ### dir was set as default


            
              
        #0. Checkout the code from the repo
        #1. Install deps of our react apps 
        #2. Exec automated tests

