name: Use Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4

            #- name: Printing folders
             # run: ls 

            - name: Setup Node
              uses:  actions/setup-node@v3
              with: 
                node-version: '20.x'

            - name: Install Dependencies
              run: npm ci
              working-directory: 4-use-actions/react-app 

            
              
        #0. Checkout the code from the repo
        #1. Install deps of our react apps 
        #2. Exec automated tests

