name: Usint Expressions

on: 
    #push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
            
jobs:
    echo:
        runs-on: ubuntu-latest

        steps:
            - name: '[debug] Print start-up'
              if: ${{inputs.debug}}
              run: |
                echo "Triggered by: ${{github.event_name}}"
                echo "Branch: ${{github.ref}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner os: ${{github.os}}"

            - name: '[debug] Print when triggered from main'
              if: ${{inputs.debu && github.ref == 'refs/head/main'}}
              run: echo "I was triggered from main"

            - name: Greeting
              run: echo "Hello world"


