name: Using caching - React APP

on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: Wether to execute cache step
        type: boolean
        default: true

jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: caching-dir/react-app
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v3
          with: 
            node-version: '20.x'

        - name: Install dependencies
          run: npm ci
        - name: testing
          run: npm run test
        - name: Build
          run: npm run build
        - name: Deploying to nonprod
          run: echo "Deploying to nonprod"



    # 1. Checkout the code
    # 2. Install dependencies
    # 3. Linting, formatting, unit testing, building
    # 4. Deploy to a nonprod environment

