name: Using caching - React APP

on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: Wether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node version
        type: choice
        options: 
            - 18.x
            - 20.x
            - 21.x
        default: 20.x



jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: caching-dir/react-app
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v3
          with: 
            node-version: ${{inputs.node-version}}
        - name: Downloade cached dependencies
          uses: actions/cache@v3
          if: ${{inputs.use-cache}}
          id: cache
          with:
            path: caching-dir/react-app/node_modules
            key: deps-node-modules-${{ hashFiles('chaching-dir/react-app/package-lock.json')}}

        - name: Install dependencies
          if: steps.cache.outpus.cache-hit != 'true'
          run: npm ci
        - name: testing
          run: npm run test
        - name: Build
          run: npm run build
        - name: Deploying to nonprod
          run: echo "Deploying to nonprod"



    # 1. Checkout the code
    # 2. Install dependencies
    # 3. Linting, formatting, unit testing, building
    # 4. Deploy to a nonprod environment

