name: Custom actions Composite

on: 
    workflow_dispatch:
env:
    working-directory: custom-actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ${{ env.working-directory}}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with:
                node-version: 20.x
                workin-dir: ${{ env.working-directory}}
            - name: Test
              run: npm run test
              #working-directory: custom-actions/react-app
            - name: Build
              run: npm run build
              #working-directory: custom-actions/react-app
              #

