name: Working with Inputs 

on: 
  workflow_dispatch:
    inputs:
        dry-run:
            type: boolean
            description: Skip deployment and print build output
            default: false
        target: 
            type: environment
            required: true
            description: Which env the workflow will target
        tag:
            type: choice
            options:
                - v1
                - v2
                - v3
            default: v3
            description: Release from which to build and deploy

jobs:
    echo:
        runs-on: ubuntu-latest




